/-
The good events of `sec:recurrent-nonstab`: some site of a gadget carries a
Pareto value above the threshold `K L_m`.

`RWRS/Support/Spike.lean` bounds the probability of one such event from below,
uniformly in the gadget.  What is added here is the passage from the cardinality
of the site set to a finite set of sites, the measurability of the event for the
sigma-algebra of its own block of coordinates, which is what makes the events of
different gadgets independent, and the two elementary steps of the second
Borel-Cantelli lemma: a series bounded below by a positive constant diverges,
and membership in the `limsup` of a sequence of sets is the infinitude of the
index set.
-/
import RWRS.Support.Spike
import LatticeProb.Prob.Blocks
import Mathlib.Probability.BorelCantelli

namespace RWRS.Support

open MeasureTheory Filter
open scoped ENNReal

variable {V : Type*}

/-! ### From a cardinality bound to a finite set of sites -/

/-- A set whose cardinality dominates `x` contains a finite set of at least `x`
sites. -/
theorem exists_finset_card_ge {A : Set V} {x : ℝ}
    (h : ENNReal.ofReal x ≤ A.encard) :
    ∃ S : Finset V, (S : Set V) ⊆ A ∧ x ≤ (S.card : ℝ) := by
  classical
  have hce : (⌈x⌉₊ : ℕ∞) ≤ A.encard := by
    rcases eq_or_ne A.encard ⊤ with htop | htop
    · rw [htop]; exact le_top
    · obtain ⟨k, hk⟩ := ENat.ne_top_iff_exists.1 htop
      rw [← hk] at h ⊢
      have hcast : (((k : ℕ∞) : ℝ≥0∞)) = ENNReal.ofReal (k : ℝ) := by
        simp [ENNReal.ofReal_natCast]
      rw [hcast] at h
      have hxk : x ≤ (k : ℝ) := by
        by_contra hlt
        exact absurd h (not_le.2
          ((ENNReal.ofReal_lt_ofReal_iff_of_nonneg (Nat.cast_nonneg k)).2 (not_le.1 hlt)))
      exact_mod_cast Nat.ceil_le.2 hxk
  obtain ⟨t, hsub, hcard⟩ := Set.exists_subset_encard_eq hce
  have hfin : t.Finite := by
    rw [← Set.encard_ne_top_iff, hcard]; simp
  refine ⟨hfin.toFinset, by simpa using hsub, ?_⟩
  have : (hfin.toFinset.card : ℕ∞) = (⌈x⌉₊ : ℕ∞) := by
    rw [← hcard, ← Set.encard_coe_eq_coe_finsetCard]
    simp
  have hc : hfin.toFinset.card = ⌈x⌉₊ := by exact_mod_cast this
  rw [hc]
  exact Nat.le_ceil x

/-! ### The event reads one block of coordinates -/

/-- The event that some site of `A` carries a value at least `c` is measurable
for the sigma-algebra generated by the coordinates in `A`. -/
theorem measurableSet_comap_spike [Countable V] (A : Set V) (c : ℝ) :
    MeasurableSet[MeasurableSpace.comap
      (fun Y : V → ℝ => A.restrict Y) inferInstance]
      {Y : V → ℝ | ∃ v ∈ A, c ≤ Y v} := by
  refine ⟨{y : ↥A → ℝ | ∃ v : ↥A, c ≤ y v}, ?_, ?_⟩
  · have : {y : ↥A → ℝ | ∃ v : ↥A, c ≤ y v} = ⋃ v : ↥A, {y : ↥A → ℝ | c ≤ y v} := by
      ext y; simp
    rw [this]
    exact MeasurableSet.iUnion fun v =>
      measurableSet_le measurable_const (measurable_pi_apply v)
  · ext Y
    simp only [Set.mem_preimage, Set.mem_setOf_eq, Set.restrict_apply, Subtype.exists]
    constructor
    · rintro ⟨v, hv, hle⟩; exact ⟨v, hv, hle⟩
    · rintro ⟨v, hv, hle⟩; exact ⟨v, hv, hle⟩

/-- The same event in the ambient sigma-algebra. -/
theorem measurableSet_spike [Countable V] (A : Set V) (c : ℝ) :
    MeasurableSet {Y : V → ℝ | ∃ v ∈ A, c ≤ Y v} := by
  have hm : Measurable (fun Y : V → ℝ => A.restrict Y) :=
    measurable_pi_lambda _ fun v => measurable_pi_apply (v : V)
  exact hm.comap_le _ (measurableSet_comap_spike A c)

/-! ### The two steps of the second Borel-Cantelli lemma -/

/-- A series in `[0,∞]` bounded below by a positive constant from some index on
diverges. -/
theorem tsum_eq_top_of_const_le {f : ℕ → ℝ≥0∞} {c : ℝ≥0∞} (hc : c ≠ 0)
    (h : ∀ k : ℕ, 1 ≤ k → c ≤ f k) : ∑' k : ℕ, f k = ⊤ := by
  have hshift : ∑' k : ℕ, f (k + 1) ≤ ∑' k : ℕ, f k :=
    ENNReal.tsum_comp_le_tsum_of_injective (fun a b hab => by omega) f
  have hconst : ∑' _ : ℕ, c = ⊤ := ENNReal.tsum_const_eq_top_of_ne_zero hc
  have hle : ∑' _ : ℕ, c ≤ ∑' k : ℕ, f (k + 1) :=
    ENNReal.tsum_le_tsum fun k => h (k + 1) (by omega)
  rw [hconst] at hle
  exact top_le_iff.1 (le_trans hle hshift)

/-- Membership in the `limsup` of a sequence of sets is the infinitude of the
set of indices at which the point is caught. -/
theorem infinite_of_mem_limsup {Ω : Type*} {E : ℕ → Set Ω} {ω : Ω}
    (h : ω ∈ Filter.limsup E atTop) : {k : ℕ | ω ∈ E k}.Infinite := by
  rw [Filter.mem_limsup_iff_frequently_mem] at h
  exact Nat.frequently_atTop_iff_infinite.1 h

end RWRS.Support
