"""Produce the Lean certificate: a machine-checked record of what is proved.

The certificate is not prose.  Every line of it is generated by running the
checkers and by asking Lean itself for each theorem's axiom closure, so a reader
can reproduce it with the commands it names and compare byte for byte.

    python3 tools/certificate.py            # write CERTIFICATE.md
    python3 tools/certificate.py --check    # verify the file on disk is current
"""

from __future__ import annotations

import hashlib
import re
import subprocess
import sys
from datetime import date
from pathlib import Path

from sync_docs import external_inputs_block, proved_companions, unconditional_names

try:
    import yaml
except ImportError:
    sys.exit("certificate.py: PyYAML is required (pip install pyyaml)")

ROOT = Path(__file__).resolve().parent.parent
MANIFEST = ROOT / "ledger" / "manifest.yaml"
OUT = ROOT / "CERTIFICATE.md"
ELAN = str(Path.home() / ".elan" / "bin")

# The three axioms of Lean's own logic.  Anything else in a closure -- above all
# `sorryAx` -- means the statement is not proved.
CLASSICAL = {"propext", "Classical.choice", "Quot.sound"}


def run(cmd: list[str], **kw) -> subprocess.CompletedProcess:
    import os
    env = {**os.environ, "PATH": ELAN + ":" + os.environ.get("PATH", "")}
    return subprocess.run(cmd, cwd=ROOT, capture_output=True, text=True, env=env, **kw)


def axiom_lines(exports: list[str]) -> dict[str, str]:
    """Ask Lean for each export's axiom closure, in one elaboration."""
    imports = sorted({f"import {m}" for m in ("RWRS.Basic",)} |
                     {f"import {p}" for p in module_names()})
    src = "\n".join(imports) + "\n" + "\n".join(f"#print axioms {e}" for e in exports) + "\n"
    probe = ROOT / "scratch" / "_certificate_probe.lean"
    probe.parent.mkdir(exist_ok=True)
    probe.write_text(src, encoding="utf-8")
    try:
        r = run(["lake", "env", "lean", str(probe)], timeout=3600)
    finally:
        probe.unlink(missing_ok=True)
    if r.returncode != 0:
        raise RuntimeError("axiom probe did not elaborate:\n" + r.stdout + r.stderr)
    out: dict[str, str] = {}
    for line in r.stdout.splitlines():
        m = re.match(r"'([^']+)' (?:depends on axioms: \[(.*)\]|does not depend on any axioms)", line)
        if m:
            out[m.group(1)] = m.group(2) or ""
    missing = sorted(set(exports) - out.keys())
    if missing:
        raise RuntimeError("missing axiom closures: " + ", ".join(missing))
    for name, axioms in out.items():
        extra = {a.strip() for a in axioms.split(",") if a.strip()} - CLASSICAL
        if extra:
            raise RuntimeError(f"{name}: nonclassical axioms {sorted(extra)}")
    return out


def module_names() -> list[str]:
    names = []
    for f in sorted((ROOT / "RWRS").rglob("*.lean")):
        names.append(str(f.relative_to(ROOT).with_suffix("")).replace("/", "."))
    return names


def frozen_hash(node: dict) -> str:
    text = (ROOT / node["file"]).read_text(encoding="utf-8")
    b = text[text.index("-- FROZEN-STATEMENT-BEGIN") + len("-- FROZEN-STATEMENT-BEGIN"):
             text.index("-- FROZEN-STATEMENT-END")]
    if b.startswith("\n"):
        b = b[1:]
    return hashlib.sha256(b.encode("utf-8")).hexdigest()


def build() -> str:
    manifest = yaml.safe_load(MANIFEST.read_text(encoding="utf-8"))
    nodes = manifest["nodes"]
    corollaries = unconditional_names()
    exports = [n["export"] for n in nodes] + corollaries
    companions = proved_companions(nodes)
    theorems = [n for n in nodes if n["kind"] == "theorem"]
    externals = [n for n in nodes if n["kind"] == "definition"]

    r = run(["lake", "build", "RWRS"], timeout=7200)
    jobs = re.search(r"Build completed successfully \((\d+) jobs\)", r.stdout)
    build_ok = r.returncode == 0
    if not build_ok:
        raise RuntimeError("certificate: Lean build failed\n" + r.stdout + r.stderr)
    for checker in ("check_manifest.py", "check_axioms.py", "check_constants.py",
                    "check_coverage.py", "sync_docs.py"):
        gate = run([sys.executable, "tools/" + checker], timeout=3600)
        if gate.returncode != 0:
            raise RuntimeError(f"certificate: {checker} failed\n" + gate.stdout + gate.stderr)
    warnings = [l for l in r.stdout.splitlines() if l.startswith("warning:")]

    ax = axiom_lines(exports)
    if set(exports) - ax.keys():
        raise RuntimeError("certificate: missing axiom closures")
    if any(set(a.strip() for a in closure.split(",") if a.strip()) - CLASSICAL
           for closure in ax.values()):
        raise RuntimeError("certificate: non-classical axiom in a closure")
    if warnings:
        raise RuntimeError("certificate: unexpected build warnings")
    sealed = sum(n["kind"] == "theorem" and n["state"] == "SEALED" for n in nodes)
    inputs = sum(n["kind"] == "definition" for n in nodes)
    toolchain = (ROOT / "lean-toolchain").read_text().strip()
    ml = re.search(r'"rev":\s*"([0-9a-f]{40})"',
                   (ROOT / "lake-manifest.json").read_text(encoding="utf-8"))
    paper = ROOT / "paper" / "rwrs.tex"
    paper_sha = hashlib.sha256(paper.read_bytes()).hexdigest()

    lines: list[str] = []
    A = lines.append
    A("# Lean certificate")
    A("")
    A("*Divisible sandpiles via random walks in random scenery*,")
    A("Bou-Rabee–Peres–Sava-Huss.  This file records what a machine has checked, and")
    A("how to check it again.  It is generated by `python3 tools/certificate.py`; do")
    A("not edit it by hand.")
    A("")
    A("## What is claimed")
    A("")
    A("The paper's registered statements are proved in Lean 4 from Mathlib and")
    A("the shared library `LatticeProb`, under the hypotheses displayed in their")
    A("frozen declarations, with no added axiom and no `sorry`.")
    A("Cited inputs are proposition-valued predicates in `RWRS/External/`,")
    A("carried as explicit hypotheses together with each theorem's own hypotheses.")
    A("Separate companion theorems discharge these predicates under the conditions")
    A("listed below; `CORRESPONDENCE.md` records the correspondence with the paper.")
    A(f"{len(companions)} of the {len(externals)} cited inputs have registered proved companions.")
    A("")
    A("## Environment")
    A("")
    A("| | |")
    A("|---|---|")
    A(f"| Lean toolchain | `{toolchain}` |")
    A(f"| Mathlib revision | `{ml.group(1) if ml else 'unknown'}` |")
    A(f"| Paper (`paper/rwrs.tex`) SHA-256 | `{paper_sha}` |")
    A(f"| Build | {'succeeded' if build_ok else 'FAILED'}"
      f"{f', {jobs.group(1)} jobs' if jobs else ''} |")
    A(f"| Build warnings | {len(warnings)} |")
    A(f"| Generated | {date.today().isoformat()} |")
    A("")
    A("## Reproducing it")
    A("")
    A("```")
    A("elan toolchain install $(cat lean-toolchain)")
    A("lake exe cache get      # optional: prebuilt Mathlib")
    A("lake build RWRS")
    A("python3 tools/check_manifest.py     # frozen statements match their hashes")
    A("python3 tools/check_axioms.py       # no axiom closure contains sorryAx")
    A("python3 tools/check_warnings.py     # the build emits no unauthorized warning")
    A("python3 tools/check_constants.py    # parameter order for uniform constants")
    A("python3 tools/sync_docs.py --write  # generate manifest and input tables")
    A("python3 tools/check_coverage.py     # every paper statement is registered")
    A("python3 tools/certificate.py --check")
    A("```")
    A("")
    A("## The theorems, and what each depends on")
    A("")
    A("`#print axioms` reports the full transitive axiom closure of a proof.  A")
    A("closure of exactly `propext, Classical.choice, Quot.sound` is classical")
    A("mathematics and nothing more; those three are Lean's own, not ours.")
    A("`sorryAx` in a closure would mean the statement is not proved.  It appears")
    A("nowhere below.")
    A("")
    A("| # | node | Lean name | state | paper | axiom closure |")
    A("|---|---|---|---|---|---|")
    clean = 0
    for i, n in enumerate(nodes, 1):
        e = n["export"]
        got = {a.strip() for a in ax[e].split(",") if a.strip()}
        extra = got - CLASSICAL
        verdict = "classical only" if not extra else "**" + ", ".join(sorted(extra)) + "**"
        if n.get("kind") == "definition":
            companion = companions.get(n["id"])
            verdict = (f"proved (companion {companion['id']}, from the Lattice-Probability library)"
                       if companion else "assumed (a cited theorem, stated as a proposition)")
        elif not extra:
            clean += 1
        src = n["source"]
        m = re.search(r"label ([A-Za-z][A-Za-z0-9:_-]*)", src) or re.search(r"\(([A-Za-z][A-Za-z0-9:_-]*)\)", src)
        paper_cell = f"`{m.group(1)}`" if m else "—"
        A(f"| {i} | `{n['id']}` | `{e}` | `{n['state']}` | {paper_cell} | {verdict} |")
    A("")
    A(f"All {clean} declarations have axiom closures contained in the three classical")
    A(f"axioms. The {sealed} theorem nodes are `SEALED`; the {inputs} external definitions")
    A("are `FROZEN`. A clean definition does not supply a proof of its proposition.")
    A("")
    A("## External inputs")
    A("")
    A(f"{clean} of {len(theorems)} registered theorem proofs depend on nothing beyond")
    A("Lean's three classical axioms. The external predicates remain definition")
    A("nodes in state `FROZEN`; their proved companions are theorem nodes in state `SEALED`.")
    A("")
    A("## Hypotheses of the proved companions")
    A("")
    A("Each companion proves its external predicate under the hypotheses below.")
    A("The hypotheses of a frozen theorem determine which companions apply at its use sites.")
    A("")
    A("| companion | Lean theorem | hypotheses |")
    A("|---|---|---|")
    scopes = {
        "X-001P": "none",
        "X-002P": "none",
        "X-003P": "none",
        "X-004P": "locally finite infinite connected graph",
        "X-006P": "locally finite infinite connected graph; `NetGood N` supplies this for `netGraph N`",
        "X-007P": "`[Countable V]`; measurability and square integrability are in the predicate",
        "X-008P": "locally finite infinite connected graph with `∀ o, green G o o ≠ ⊤`",
    }
    for companion in sorted(companions.values(), key=lambda n: n["id"]):
        scope = scopes.get(companion["id"])
        if scope is None:
            raise RuntimeError(f"companion scope is not recorded: {companion['id']}")
        A(f"| `{companion['id']}` | `{companion['export']}` | {scope} |")
    if corollaries:
        A("")
        A("## Corollaries with cited inputs discharged")
        A("")
        A("These corollaries apply the frozen theorems to proved companions and retain")
        A("all their other hypotheses. Their axiom closures are checked with the registered proofs.")
        A("")
        A("| Lean theorem | axioms |")
        A("|---|---|")
        for name in corollaries:
            A(f"| `{name}` | classical only |")
    A("")
    A(external_inputs_block(nodes))
    A("")
    A("## Frozen statements")
    A("")
    A("The bytes of each statement are pinned, so a statement cannot be weakened")
    A("after the fact without the hash changing.  `tools/check_manifest.py`")
    A("verifies these; the recipe is in `CORRESPONDENCE.md`.")
    A("")
    A("| node | SHA-256 of the frozen statement |")
    A("|---|---|")
    for n in nodes:
        h = frozen_hash(n)
        flag = "" if h == n["frozen_sha256"] else "  ← MISMATCH"
        A(f"| `{n['id']}` | `{h}`{flag} |")
    A("")
    A("## What is not claimed")
    A("")
    A("- The cited theorems in `RWRS/External/` (the rows marked *assumed* above) are")
    A("  not proved here; each statement that uses one carries it as an explicit")
    A("  hypothesis. Companion proofs apply under the hypotheses listed above.")
    A("- The paper's open questions (Section 9) are questions; nothing there is")
    A("  formalized, and nothing here bears on them.")
    A("- The proof ideas and the related work of Sections 1.1 and 1.2 are")
    A("  outside the formalization.")
    A("")
    return "\n".join(lines) + "\n"


def main() -> int:
    try:
        text = build()
    except (RuntimeError, subprocess.TimeoutExpired) as error:
        print(f"certificate: {error}", file=sys.stderr)
        return 1
    if "--check" in sys.argv[1:]:
        if not OUT.exists():
            print("certificate: CERTIFICATE.md is missing", file=sys.stderr)
            return 1
        cur = OUT.read_text(encoding="utf-8")
        # the generation date is allowed to differ
        strip = lambda s: re.sub(r"\| Generated \| .* \|", "", s)
        if strip(cur) != strip(text):
            print("certificate: CERTIFICATE.md is out of date; regenerate it",
                  file=sys.stderr)
            return 1
        print("certificate: OK (CERTIFICATE.md matches the checked state)")
        return 0
    OUT.write_text(text, encoding="utf-8")
    print(f"certificate: wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
