"""Regenerate the manifest-derived tables in README.md and CORRESPONDENCE.md.

Both documents restate what `ledger/manifest.yaml` already records: how many
nodes exist, what state each is in, and where in the paper each one comes from.
Everything between a BEGIN/END marker pair below is generated from the
manifest and the proved companion and corollary declarations.

    python3 tools/sync_docs.py            # check, exit 1 if a block is stale
    python3 tools/sync_docs.py --write    # regenerate the blocks in place
"""

from __future__ import annotations

import re
import sys
from collections import Counter
from pathlib import Path

try:
    import yaml
except ImportError:
    sys.exit("sync_docs.py: PyYAML is required (pip install pyyaml)")

ROOT = Path(__file__).resolve().parent.parent
MANIFEST = ROOT / "ledger" / "manifest.yaml"

SURFACE_BEGIN = "<!-- FROZEN-SURFACE-BEGIN (generated by tools/sync_docs.py) -->"
SURFACE_END = "<!-- FROZEN-SURFACE-END -->"
STATUS_BEGIN = "<!-- STATUS-BEGIN (generated by tools/sync_docs.py) -->"
STATUS_END = "<!-- STATUS-END -->"
INPUTS_BEGIN = "<!-- CITED-INPUTS-BEGIN (generated by tools/sync_docs.py) -->"
INPUTS_END = "<!-- CITED-INPUTS-END -->"
HYPOTHESES_BEGIN = "<!-- INPUT-HYPOTHESES-BEGIN (generated by tools/sync_docs.py) -->"
HYPOTHESES_END = "<!-- INPUT-HYPOTHESES-END -->"


LABEL_RE = re.compile(r"label ([A-Za-z][A-Za-z0-9:_-]*)")
RANGE_RE = re.compile(r"rwrs\.tex:\d+-\d+")


def paper_cell(source: str) -> str:
    """The `paper` column: line range plus label, or the guard's own wording."""
    rng = RANGE_RE.search(source)
    lab = LABEL_RE.search(source)
    if rng and lab:
        return f"`{rng.group(0)}`, `{lab.group(1)}`"
    return source


def surface_table(nodes: list[dict]) -> str:
    rows = ["| id | Lean | paper | state |", "|---|---|---|---|"]
    for n in nodes:
        rows.append(
            f"| `{n['id']}` | `{n['export']}` | {paper_cell(n['source'])} "
            f"| {n['state']} |")
    return "\n".join(rows)


def proved_companions(nodes: list[dict]) -> dict[str, dict]:
    """The SEALED theorem registered beside each external predicate."""
    sealed = {n["id"]: n for n in nodes
              if n["kind"] == "theorem" and n["state"] == "SEALED"}
    return {n["id"]: sealed[n["id"] + "P"] for n in nodes
            if n["kind"] == "definition" and n["id"] + "P" in sealed}


def unconditional_names() -> list[str]:
    """The corollaries that discharge every cited input at their use sites."""
    path = ROOT / "RWRS" / "Support" / "Unconditional.lean"
    if not path.exists():
        return []
    return re.findall(r"(?m)^theorem (RWRS\.[A-Za-z0-9_]+_unconditional)\b",
                      path.read_text(encoding="utf-8"))


def status_block(nodes: list[dict]) -> str:
    counts = Counter(n["state"] for n in nodes)
    companions = proved_companions(nodes)
    draft = [n["id"] for n in nodes if n["state"] == "DRAFT_SORRY"]
    sentence = (
        f"{len(nodes)} registered nodes: {counts['SEALED']} SEALED "
        f"(statements of the paper, proved), {counts['FROZEN']} FROZEN "
        f"(cited external inputs, stated as hypotheses; {len(companions)} "
        "of them with a proved companion)")
    other = [f"{count} {state}" for state, count in sorted(counts.items())
             if state not in {"SEALED", "FROZEN"}]
    if other:
        sentence += "; " + ", ".join(other)
    paper_sealed = sum(n["id"].startswith("N-") and n["state"] == "SEALED" for n in nodes)
    body = [f"Status: **{sentence}.**", "",
            f"The SEALED count includes {paper_sealed} paper statements and "
            f"{len(companions)} companion theorems. Their proofs are machine-checked,",
            "and their axiom closures contain only Lean's classical axioms.",
            "Run `python3 tools/check_axioms.py` to verify the registered theorems."]
    if draft:
        body += ["", "Proofs in progress: " + ", ".join(f"`{nid}`" for nid in draft) + "."]
    if companions:
        body += ["", "Proved companions: " + ", ".join(
            f"`{nid}` → `{companion['id']}`" for nid, companion in sorted(companions.items())) + ".",
            "Companions discharge a cited input under their own hypotheses;",
            "see [the certificate](CERTIFICATE.md) for their scope."]
    names = unconditional_names()
    if names:
        body += ["", "Corollaries with every cited input discharged:", ""]
        body += [f"- `{name}`" for name in names]
        body += ["", "These retain the other hypotheses of the corresponding frozen statements."]
    body += ["", "This section is generated by `python3 tools/sync_docs.py --write`."]
    return "\n".join(body)


def external_inputs_block(nodes: list[dict]) -> str:
    inputs = [n for n in nodes if n["kind"] == "definition"]
    rows = [
        f"The manifest registers {len(inputs)} external propositions. A proposition's",
        "axiom closure checks its definition; a witness theorem proves the input",
        "under the witness's stated hypotheses.",
        "",
        "| input | proposition | source | proved witness |",
        "|---|---|---|---|",
    ]
    companions = proved_companions(nodes)
    for n in inputs:
        companion = companions.get(n["id"])
        witness = (f"`{companion['export']}` (`{companion['id']}`)" if companion else "—")
        rows.append(f"| `{n['id']}` | `{n['export']}` | {n['source']} | {witness} |")
    rows.extend([
        "",
        "`X-005` is the pointwise transition estimate",
        "`P_x(X_n = y) ≤ 2 sqrt(deg(y)/deg(x)) exp(-dist(x,y)^2/(2n))`,",
        "for `n ≥ 1` on a connected, nontrivial, locally finite graph with measurable",
        "singletons. Its sources are Carne (1985), Varopoulos (1985), and",
        "[Lyons–Peres, Theorem 13.4](https://rdlyons.pages.iu.edu/prbtree/book_pb.pdf).",
        "`RWRS/Support/DisplacementAtOrigin.lean` combines this input with a degree bound",
        "and polynomial volume growth at the origin to prove the exit estimates at",
        "radii `⌈N^(1/2+s)⌉`, `s > 0`, used in stabilization part (ii).",
        "The constants may depend on the origin and on `s`.",
    ])
    return "\n".join(rows)


def external_hypotheses_table(nodes: list[dict]) -> str:
    inputs = {n["export"]: n["id"] for n in nodes if n["kind"] == "definition"}
    rows = ["| theorem node | external propositions in the frozen statement |",
            "|---|---|"]
    for n in nodes:
        if n["kind"] != "theorem":
            continue
        text = (ROOT / n["file"]).read_text(encoding="utf-8")
        statement = text.split("-- FROZEN-STATEMENT-BEGIN", 1)[1].split(
            "-- FROZEN-STATEMENT-END", 1)[0]
        names = sorted(set(re.findall(r"RWRS\.External\.[A-Za-z][A-Za-z0-9_]*", statement)))
        ids = [inputs[name] for name in names if name in inputs]
        if ids:
            rows.append(f"| `{n['id']}` | " + ", ".join(f"`{i}`" for i in ids) + " |")
    return "\n".join(rows)


def splice(text: str, begin: str, end: str, body: str) -> str:
    i, j = text.find(begin), text.find(end)
    if i < 0 or j < 0:
        raise LookupError(f"missing marker pair {begin!r}")
    return text[:i] + begin + "\n\n" + body + "\n\n" + text[j:]


def main() -> int:
    write = "--write" in sys.argv[1:]
    nodes = (yaml.safe_load(MANIFEST.read_text(encoding="utf-8")) or {}).get("nodes") or []

    targets = [
        (ROOT / "CORRESPONDENCE.md", SURFACE_BEGIN, SURFACE_END, surface_table(nodes)),
        (ROOT / "README.md", STATUS_BEGIN, STATUS_END, status_block(nodes)),
        (ROOT / "CORRESPONDENCE.md", INPUTS_BEGIN, INPUTS_END, external_inputs_block(nodes)),
        (ROOT / "CORRESPONDENCE.md", HYPOTHESES_BEGIN, HYPOTHESES_END,
         external_hypotheses_table(nodes)),
    ]

    desired = {}
    original = {}
    for path, begin, end, body in targets:
        if path not in original:
            original[path] = path.read_text(encoding="utf-8")
        text = desired.get(path, original[path])
        try:
            want = splice(text, begin, end, body)
        except LookupError as exc:
            print(f"sync_docs: {path.name}: {exc}", file=sys.stderr)
            return 2
        desired[path] = want
    stale = [(path, want) for path, want in desired.items() if want != original[path]]

    if not stale:
        print(f"sync_docs: OK ({len(nodes)} nodes; README.md and "
              f"CORRESPONDENCE.md agree with the manifest)")
        return 0

    for path, want in stale:
        print(f"  stale: {path.relative_to(ROOT)}")
        if write:
            path.write_text(want, encoding="utf-8")

    if not write:
        print("\nsync_docs: rerun with --write to regenerate", file=sys.stderr)
        return 1
    print(f"\nsync_docs: regenerated {len(stale)} file(s)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
